### ISSUE TITLE
show errors on the line they occur instead of below

### ISSUE THREAD

**Issue by cedric-h** [hackclub/gamelab#14]
zach suggested this during a meeting and it just makes sense

**Comment by maxwofford** [comment]
<img width="1151" alt="Screen Shot 2022-01-25 at 16 12 22" src="https://user-images.githubusercontent.com/5891442/151060553-3237a87a-5253-4ad5-a9b3-a7d3d23c0774.png">

**Comment by maxwofford** [comment]
I'm not totally sure if this should have tag:bug, or tag:enhancement. Moving the error indicator to the line itself is an enhancement, but the error says it's on dispatch.js:88, which is incorrect (to the user, it's on line 7 & not in dispatch.js). Does this ticket also include fixing up the error message to mention the place the user's code errored?

**Comment by YodaLightsabr** [comment]
I've done a bit of research and I have a few findings to report.

Because of how JavaScript `new Function` works, it checks for syntax errors, and since the line where it checks for the syntax error isn't in the actual code, it just says it's at `new Function()` and provides no more detail. However, when it's a runtime error, since it was found within the code, it shows you exactly where it is.

| Syntax error: | Runtime error: |
| ------------- | -------------- |
| ![Syntax error](https://yodacode.xyz/F81c4b3fa0e.png) | ![Runtime error](https://yodacode.xyz/Fc830b250dd.png) |

We might be able to get around the syntax errors by putting it through some kind of validator and showing the error from there if it finds one. For the runtime error, we would just need to parse the error string for the line number and column number, and then subtract the line by 2 (because it's starting at 3 for some reason) and the column number by 6 because it starts at 7.

**Comment by leomcelroy** [comment]
Implemented this when possible with new error messages.
